name: Rust

on:
  push:
    branches:
      - main
      - wip/**
  pull_request:
    branches:
      - main
      - wip/**
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install required system libraries (ALSA hooks)
      run: sudo apt-get install --fix-missing libasound2-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
